
services:

  app:
    build: .
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATABASE=postgres

    ports:
    - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 5s
      retries: 20

