version: "3.8"

services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  app:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: ibmcom/informix-developer-database:latest
    restart: unless-stopped
    environment:
      - LICENSE=accept
      - INFORMIXDB_SERVER=informix
      - INFORMIXDB_USERNAME=informix
      - INFORMIXDB_PASSWORD=in4mix

    ports:
      - "9088:9088"
    healthcheck:
      test: ["CMD-SHELL", "onstat -"]
      timeout: 5s
      retries: 20