//package JOOQ.extendedPojos;
//
///*
// * This file is generated by jOOQ.
// */
//
//
//import JOOQ.repositories.TerminalIdRepository;
//import com.github.javafaker.Faker;
//import no.ntnu.bachelor_group3.dataaccessevaluation.jooq.model.tables.pojos.TerminalId;
//import org.jooq.DSLContext;
//import org.jooq.meta.derby.sys.Sys;
//
//import java.util.Random;
//
//import static no.ntnu.bachelor_group3.dataaccessevaluation.jooq.model.Tables.TERMINAL_ID;
//import static no.ntnu.bachelor_group3.dataaccessevaluation.jooq.model.Tables.VALID_POSTAL_CODES;
//
//
///**
// * This class is generated by jOOQ.
// */
//@SuppressWarnings({ "all", "unchecked", "rawtypes" })
//public class CustomCustomerPojo {
//    private DSLContext dslContext;
//
//    TerminalIdRepository terminalIdRepository = new TerminalIdRepository(dslContext);
//    private static long counter = 1L;
//    Faker faker = new Faker();
//
//    private static final long serialVersionUID = 1L;
//
//    private Long customerId;
//    private String address;
//    private String name;
//    private String zipCode;
//
//    private Integer terminalId;
//
//
//
//
//
//    public CustomCustomerPojo(DSLContext dslContext) {
//        int randomZipCode = new Random().nextInt(5139) + 1;
//        while (!dslContext.fetchExists(VALID_POSTAL_CODES.where(VALID_POSTAL_CODES.POSTAL_CODE.eq(String.valueOf(randomZipCode))))) {
//           randomZipCode = new Random().nextInt(5139) + 1;
//        }
//        this.customerId = counter++;
//        this.address = faker.address().streetAddress();
//        this.name = faker.name().fullName();
//        this.zipCode = String.format("%04d", randomZipCode);
//        this.terminalId = dslContext.selectFrom(TERMINAL_ID).where(TERMINAL_ID.POSTAL_CODE.eq(zipCode)).fetchOneInto(TerminalId.class).getTerminalIdTerminalId();
//        System.out.println(zipCode);
//
//    }
//
//
//
//    public CustomCustomerPojo(
//            Long customerId,
//            String address,
//            String name,
//            String zipCode,
//            Integer terminalId
//    ) {
//        this.customerId = customerId;
//        this.address = address;
//        this.name = name;
//        this.zipCode = zipCode;
//        this.terminalId = terminalId;
//    }
//
//    /**
//     * Getter for <code>public.customer.customer_id</code>.
//     */
//    public Long getCustomerId() {
//        return this.customerId;
//    }
//
//    /**
//     * Setter for <code>public.customer.customer_id</code>.
//     */
//    public CustomCustomerPojo setCustomerId(Long customerId) {
//        this.customerId = customerId;
//        return this;
//    }
//
//    /**
//     * Getter for <code>public.customer.address</code>.
//     */
//    public String getAddress() {
//        return this.address;
//    }
//
//    /**
//     * Setter for <code>public.customer.address</code>.
//     */
//    public CustomCustomerPojo setAddress(String address) {
//        this.address = address;
//        return this;
//    }
//
//    /**
//     * Getter for <code>public.customer.name</code>.
//     */
//    public String getName() {
//        return this.name;
//    }
//
//    /**
//     * Setter for <code>public.customer.name</code>.
//     */
//    public CustomCustomerPojo setName(String name) {
//        this.name = name;
//        return this;
//    }
//
//    /**
//     * Getter for <code>public.customer.zip_code</code>.
//     */
//    public String getZipCode() {
//        return this.zipCode;
//    }
//
//    /**
//     * Setter for <code>public.customer.zip_code</code>.
//     */
//    public CustomCustomerPojo setZipCode(String zipCode) {
//        this.zipCode = zipCode;
//        return this;
//    }
//
//    /**
//     * Getter for <code>public.customer.terminal_id</code>.
//     */
//
//    public Integer getTerminalId() {
//        return this.terminalId;
//    }
//
//    /**
//     * Setter for <code>public.customer.terminal_id</code>.
//     */
//    public CustomCustomerPojo setTerminalId(Integer terminalId) {
//        this.terminalId = terminalId;
//        return this ;
//    }
//    @Override
//    public int hashCode() {
//        final int prime = 31;
//        int result = 1;
//        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
//        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
//        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
//        result = prime * result + ((this.zipCode == null) ? 0 : this.zipCode.hashCode());
//        result = prime * result + ((this.terminalId == null) ? 0 : this.terminalId.hashCode());
//        return result;
//    }
//
//    @Override
//    public String toString() {
//        StringBuilder sb = new StringBuilder("Customer (");
//
//        sb.append(customerId);
//        sb.append(", ").append(address);
//        sb.append(", ").append(name);
//        sb.append(", ").append(zipCode);
//        sb.append(", ").append(terminalId);
//
//        sb.append(")");
//        return sb.toString();
//    }
//}
